### ISSUE TITLE
Github Pages Deployment for Portfolio project

### ISSUE THREAD

**Issue by SirriCelles** [SirriCelles/portfolio#15]
## Github Pages Deployment for Portfolio project

- Found below is the live demo for my portfolio app hosted via GitHub pages.
[Live demo link](https://sirricelles.github.io/portfolio/)
- This Deployment points to the main branch. It has an updated readme.

**Comment by zieeco** [comment]
# status: APPROVED :green_circle: :100: 

Hi, @SirriCelles 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 
✅ Live demo link working as expected 👏 



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SirriCelles** [comment]
Thank You
